### ISSUE TITLE
error TS2339: Property 'customIcon' does not exist on type '{ url: string; disabled: false; }'

### ISSUE THREAD

**Issue by d0rich** [exactpro/docs-toolkit#20]
**Describe the bug**
When I am trying to use toolkit as Nuxt layer, I see following error during typecheck:

```shell
Error: node_modules/@exactpro/docs-web-toolkit/components/ep/layout/FooterSocial.vue(32,33): error TS2339: Property 'customIcon' does not exist on type '{ url: string; disabled: false; }'.
Error: node_modules/@exactpro/docs-web-toolkit/components/ep/layout/FooterSocial.vue(37,57): error TS2339: Property 'customIcon' does not exist on type '{ url: string; disabled: false; }'.
Error: node_modules/@exactpro/docs-web-toolkit/components/ep/layout/FooterSocial.vue(42,32): error TS2339: Property 'url' does not exist on type '{ disabled: true; } | (Omit<{ disabled: true; }, "disabled"> & Omit<SocialLinkConfigOptions, "disabled"> & { disabled: boolean; })'.
  Property 'url' does not exist on type '{ disabled: true; }'.
Error: node_modules/@exactpro/docs-web-toolkit/components/ep/layout/FooterSocial.vue(46,34): error TS2339: Property 'customIcon' does not exist on type '{ disabled: true; } | (Omit<{ disabled: true; }, "disabled"> & Omit<SocialLinkConfigOptions, "disabled"> & { disabled: boolean; })'.
  Property 'customIcon' does not exist on type '{ disabled: true; }'.
Error: node_modules/@exactpro/docs-web-toolkit/components/ep/layout/FooterSocial.vue(51,58): error TS2339: Property 'customIcon' does not exist on type '{ disabled: true; } | (Omit<{ disabled: true; }, "disabled"> & Omit<SocialLinkConfigOptions, "disabled"> & { disabled: boolean; })'.
  Property 'customIcon' does not exist on type '{ disabled: true; }'.
Error: node_modules/@exactpro/docs-web-toolkit/components/ep/layout/FooterSocial.vue(56,31): error TS2339: Property 'url' does not exist on type '{ disabled: true; } | (Omit<{ disabled: true; }, "disabled"> & Omit<SocialLinkConfigOptions, "disabled"> & { disabled: boolean; })'.
  Property 'url' does not exist on type '{ disabled: true; }'.
Error: node_modules/@exactpro/docs-web-toolkit/components/ep/layout/FooterSocial.vue(60,33): error TS2339: Property 'customIcon' does not exist on type '{ disabled: true; } | (Omit<{ disabled: true; }, "disabled"> & Omit<SocialLinkConfigOptions, "disabled"> & { disabled: boolean; })'.
  Property 'customIcon' does not exist on type '{ disabled: true; }'.
Error: node_modules/@exactpro/docs-web-toolkit/components/ep/layout/FooterSocial.vue(65,57): error TS2339: Property 'customIcon' does not exist on type '{ disabled: true; } | (Omit<{ disabled: true; }, "disabled"> & Omit<SocialLinkConfigOptions, "disabled"> & { disabled: boolean; })'.
  Property 'customIcon' does not exist on type '{ disabled: true; }'.
Error: node_modules/@exactpro/docs-web-toolkit/components/ep/layout/FooterSocial.vue(70,32): error TS2339: Property 'url' does not exist on type '{ disabled: true; } | (Omit<{ disabled: true; }, "disabled"> & Omit<SocialLinkConfigOptions, "disabled"> & { disabled: boolean; })'.
  Property 'url' does not exist on type '{ disabled: true; }'.
Error: node_modules/@exactpro/docs-web-toolkit/components/ep/layout/FooterSocial.vue(74,34): error TS2339: Property 'customIcon' does not exist on type '{ disabled: true; } | (Omit<{ disabled: true; }, "disabled"> & Omit<SocialLinkConfigOptions, "disabled"> & { disabled: boolean; })'.
  Property 'customIcon' does not exist on type '{ disabled: true; }'.
Error: node_modules/@exactpro/docs-web-toolkit/components/ep/layout/FooterSocial.vue(79,58): error TS2339: Property 'customIcon' does not exist on type '{ disabled: true; } | (Omit<{ disabled: true; }, "disabled"> & Omit<SocialLinkConfigOptions, "disabled"> & { disabled: boolean; })'.
  Property 'customIcon' does not exist on type '{ disabled: true; }'.
Error: node_modules/@exactpro/docs-web-toolkit/components/ep/layout/FooterSocial.vue(84,31): error TS2339: Property 'url' does not exist on type '{ disabled: true; } | (Omit<{ disabled: true; }, "disabled"> & Omit<SocialLinkConfigOptions, "disabled"> & { disabled: boolean; })'.
  Property 'url' does not exist on type '{ disabled: true; }'.
Error: node_modules/@exactpro/docs-web-toolkit/components/ep/layout/FooterSocial.vue(87,33): error TS2339: Property 'customIcon' does not exist on type '{ disabled: true; } | (Omit<{ disabled: true; }, "disabled"> & Omit<SocialLinkConfigOptions, "disabled"> & { disabled: boolean; })'.
  Property 'customIcon' does not exist on type '{ disabled: true; }'.
Error: node_modules/@exactpro/docs-web-toolkit/components/ep/layout/FooterSocial.vue(92,57): error TS2339: Property 'customIcon' does not exist on type '{ disabled: true; } | (Omit<{ disabled: true; }, "disabled"> & Omit<SocialLinkConfigOptions, "disabled"> & { disabled: boolean; })'.
  Property 'customIcon' does not exist on type '{ disabled: true; }'.
Error:  Command failed with exit code 2: vue-tsc --noEmit
  at makeError (node_modules/nuxi/dist/shared/nuxi.63bda57d.mjs:625:[11](https://github.com/gevamu/gevamu.github.io/actions/runs/5178375478/jobs/9329803383#step:6:12))
  at handlePromise (node_modules/nuxi/dist/shared/nuxi.63bda57d.mjs:1114:26)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object.invoke (node_modules/nuxi/dist/chunks/typecheck.mjs:54:7)
  at async _main (node_modules/nuxi/dist/cli.mjs:49:20)
Error: Process completed with exit code 1.
```

**To Reproduce**
1. Install repository as dependency
2. Configure nuxt layer
3. Partially cusomize footer social media links
4. Run `npx nuxi typecheck`
5. See error

**Expected behavior**
No errors during typecheck.

**Additional context**
Appeared in https://github.com/gevamu/gevamu.github.io/pull/8

**Comment by d0rich** [comment]
Possible solution - define schema like here: https://github.com/shuriken-ui/nuxt/blob/main/nuxt.schema.ts
